### ISSUE TITLE
possible memory leak

### ISSUE THREAD

**Issue by michielbdejong** [michielbdejong/snickers-proxy#13]
Proxy attempt 0 of 50 (spaced at 300ms) 172.17.0.2
Proxy attempt 1 of 50 (spaced at 300ms) 172.17.0.2
Proxy attempt 2 of 50 (spaced at 300ms) 172.17.0.2
Proxy attempt 3 of 50 (spaced at 300ms) 172.17.0.2
Proxy attempt 4 of 50 (spaced at 300ms) 172.17.0.2
Proxy attempt 5 of 50 (spaced at 300ms) 172.17.0.2
Proxy attempt 6 of 50 (spaced at 300ms) 172.17.0.2
Proxy attempt 7 of 50 (spaced at 300ms) 172.17.0.2
Proxy attempt 8 of 50 (spaced at 300ms) 172.17.0.2
Proxy attempt 9 of 50 (spaced at 300ms) 172.17.0.2
Proxy attempt 10 of 50 (spaced at 300ms) 172.17.0.2
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at IncomingMessage.addListener (events.js:160:15)
    at IncomingMessage.Readable.on (_stream_readable.js:707:33)
    at Array.stream [as 3](/home/michiel/indiehosters/snickers/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:125:9)
    at ProxyServer.<anonymous> (/home/michiel/indiehosters/snickers/node_modules/http-proxy/lib/http-proxy/index.js:80:21)
    at proxyTo (/home/michiel/indiehosters/snickers/dispatcher.js:12:9)
    at null._onTimeout (/home/michiel/indiehosters/snickers/dispatcher.js:18:9)
    at Timer.listOnTimeout [as ontimeout](timers.js:112:15)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at IncomingMessage.addListener (events.js:160:15)
    at IncomingMessage.Readable.on (_stream_readable.js:707:33)
    at Array.stream [as 3](/home/michiel/indiehosters/snickers/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:130:9)
    at ProxyServer.<anonymous> (/home/michiel/indiehosters/snickers/node_modules/http-proxy/lib/http-proxy/index.js:80:21)
    at proxyTo (/home/michiel/indiehosters/snickers/dispatcher.js:12:9)
    at null._onTimeout (/home/michiel/indiehosters/snickers/dispatcher.js:18:9)
    at Timer.listOnTimeout [as ontimeout](timers.js:112:15)

**Comment by michielbdejong** [comment]
Mem usage increased to 120Mb in 7 days, so that's bad.
